//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketball1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public short year { get; set; }
        public short Team1 { get; set; }
        public short Team2 { get; set; }
        public string score { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual team team { get; set; }
        public virtual team team3 { get; set; }
    }
}
