//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketball1
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public short new_id { get; set; }
        public string title { get; set; }
        public string authoruname { get; set; }
        public string content { get; set; }
        public string img_name { get; set; }
        public System.DateTime add_date { get; set; }
    }
}
