//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketball1
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        public short playerid { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<short> team_id { get; set; }
        public Nullable<short> age { get; set; }
        public string picture { get; set; }
    
        public virtual team team { get; set; }
    }
}
